---

-  hosts: all
   become: true
   tasks:

    - name: update repository index
      apt: 
       update_cache: yes

    - name: install appache2 on repository
      apt:
       name: apache2

    - name: add php support for appache
      apt: 
       name: libapache2-mod-php 
