---

-  hosts: all
   become: true
   pre_tasks:

    - name: install updates
      tags: always
      package:
       upgrade: dist
       update_cache: yes

-  hosts: all
   become: true
   tasks:

    - name: create larry user
      tags: always
      user:
        name: larry
        groups: root

    - name: add sudoers file for larry
      tags: always
      copy:
        src: sudoer_larry
        dest: /etc/sudoers.d/larry
        owner: root
        group: root
        mode: 0440


-  hosts: web_servers
   become: true
   tasks:

    - name: install apache and php
      tags: apache, php
      package:
        name: 
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes


